[package]
name = "private-key-to-address"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = "0.10.6"
ethereum-types = "0.14.1"
hex = "0.4.3"
secp256k1 = "0.25.0"
anyhow = "1"
